language: android
dist: trusty

android:
  components:
    - tools
    - platform-tools
    # BuildTools version used by Android project
    - build-tools-28.0.3

    # The Android SDK used to compile the Android project
    - android 28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

  before_install:
    - cd project-folder/
    - chmod +x gradlew
    - gem update --system
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet

  script:
    - ./gradlew clean
    - ./gradlew build
    - ./gradlew dokka

  notifications:
    slack:
      rooms:
        secure:
      on_success: always
      on_failure: always